### ISSUE TITLE
Vim-R-plugin prevents me from running :Gdiff

### ISSUE THREAD

**Issue by chiphogg** [jcfaria/Vim-R-plugin#143]
When I edit a `.Rnw` file in a git repository, I like to run `:Gdiff` (from [fugitive](https://github.com/tpope/vim-fugitive)) to see my changes.

When I do that, I get:
```
Error detected while processing function Run_SyncTeX:
line    8:
E472: Command failed
```
Of course, the first and third lines are in angry red type.

It looks like [this line](https://github.com/jcfaria/Vim-R-plugin/blob/2becc448c718c523df41c5c9779de13274f0a4f7/ftplugin/rnoweb_rplugin.vim#L543) is the problem.  This makes sense, because `:Gdiff` opens up a file in `fugitive://`, and it's not surprising that `:cd` and `expand("%:p:h")` lead to some confusing results.

The workaround for now is to add the following to my `.vimrc`:
```vim
let g:disable_r_ftplugin = 1
```

**Comment by jalvesaq** [comment]
The bug is finally fixed: https://github.com/jcfaria/Vim-R-plugin/commit/45fbae3f25d97e2615784aaca24af71cc8392f29
