### ISSUE TITLE
Windows 7 (64-bit) problem with the newest plugin version

### ISSUE THREAD

**Issue by 10p10110111xxi11p00100100** [jcfaria/Vim-R-plugin#144]
System:
* Vim-R-Plugin: 1.1.1 (2014-12-01) {obtained through Vundle: "Bundle 'jcfaria/Vim-R-plugin'")
* Windows 7 (64-bit)
* R: 3.1.1 (2014-07-10); Platform: x86_64-w64-mingw32/x64 (64-bit)

Some previous (some weeks ago) version of Vim-R-Plugin worked perfectly, but after the recent update, I get the following errors in gVim:
```
R executable not found: 'R' [Press <Enter> to continue]
```
when typing in gVim command-line: ```:set ft=R```

```
R executable "        C:\R\R-3.1.1\bin\Rgui.exe" not found.
```
when using gVim shortcut ```\rf``` to start Rgui.exe.

My ```Rgui.exe``` is by default in: ```C:\R\R-3.1.1\bin\x64\Rgui.exe``` or ```C:\R\R-3.1.1\bin\i386\Rgui.exe```.

**Comment by jalvesaq** [comment]
It works on Windows now (tested on Windows 8): https://github.com/jalvesaq/VimCom/commit/be02eae44cb8a1a4a372a95d0894921184819065 and https://github.com/jcfaria/Vim-R-plugin/commit/48d5fc96753993d7d8e189cf84833d7b46732f48

Known issues:

  - The plugin raises the R Console window before pasting the command.
  - If GVim is 32bit, R will be 32 bit too.
  - \rh pressed in the Object Browser does not work.

I may have time to look at these issues (and at any other that is reported) on the next weekend.

**Comment by 10p10110111xxi11p00100100** [comment]
Works on Windows 7 as well.

**Comment by jalvesaq** [comment]
Thanks for testing, and, please, report the problems that you find.

**Comment by 10p10110111xxi11p00100100** [comment]
I think I can close this issue?
