### ISSUE TITLE
Syntax highlight problem in inline block when variable name contains underline

### ISSUE THREAD

**Issue by yanlinlin82** [jcfaria/Vim-R-plugin#150]
Underline in variable name should not be treated as "emphasis". For example:

    Show a value: **`r a_b`**

**Comment by jalvesaq** [comment]
Thanks for reporting the bug, but the region starting with `**` is defined by syntax/markdown.vim and I don't know how to fix the issue in syntax/rmd.vim.

**Comment by yanlinlin82** [comment]
Intuitively thinking, syntax/markdown.vim should know nothing about the code chunks. That should probably be the reason of wrongly "emphasis". Will changing render order help to solve the problem?

**Comment by jalvesaq** [comment]
I've tried to include markdown syntax at the end of syntax/rmd.vim, but the result was the same.

**Comment by yanlinlin82** [comment]
I guess this should be an issue of syntax/markdown.vim rather than syntax/rmd.vim, since two lines in the following code snippet behave differently in vim highlight:

    This is a test code chunk: `r a_b`.

    This is another _test code chunk: `r a_b`_.

**Comment by yanlinlin82** [comment]
I found there have been issues about this problem, but unfortunately no any _correct solution_ yet.

https://github.com/tpope/vim-markdown/pull/16
https://github.com/tpope/vim-markdown/issues/37
https://github.com/tpope/vim-markdown/issues/27

**Comment by jalvesaq** [comment]
I guess that the solution (if any exists) might be in the use of the `contains` option in Markdown, but I also have tried to add/remove some `contains` to/from syntax/markdown.vim and couldn't find a solution.

**Comment by jalvesaq** [comment]
I deleted from the Vim-R-plugin the files that are already distributed as official Vim runtime files. Now, there is a new repository with these files: https://github.com/jalvesaq/R-Vim-runtime

Since the official runtime files are no longer in this repository, I'm closing this bug. This bug is already described in the *Known bugs* section of the README.md, and new bugs should be reported in the new repository.
