### ISSUE TITLE
Omnicompletion crash in Mac OS

### ISSUE THREAD

**Issue by jomuller** [jcfaria/Vim-R-plugin#155]
On MacOS X 10.10.2, with R version 3.1.2 (2014-10-31) and vim-r-plugin actual dev version, omnicompletion crash

## What I did ?

I cloned vim-r-plugin from this repo to by `~/.vim/bundle/` directory and used Pathogen. I followed all the installation instruction (I hope), including adding `alias vim="vim --servername VIM"` to my `~/.bash_profile/`

I starded vim with `vim test.R`, starded R from vim send some code to R without any problem. Object browser work perfectly too. I was able to access to the R documentation from Vim.

When I tried to omnicomplete with <kbd>ctrl</kbd> + <kbd>x</kbd> + <kbd>o</kbd>, I got the following results

## What I got

This error message in Vim

> No reply
> Error detected while processing function rcomplete#CompleteR:
> line   19:
> E121: Undefined variable: g:rplugin_liblist
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   19:
> E116: Invalid arguments for function len(g:rplugin_liblist) == 0
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   19:
> E15: Invalid expression: len(g:rplugin_liblist) == 0
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   23:
> E121: Undefined variable: g:rplugin_liblist
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   23:
> E15: Invalid expression: g:rplugin_liblist + g:rplugin_globalenvlines
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   27:
> E121: Undefined variable: flines
> Press ENTER or type command to continue
> Error detected while processing function rcomplete#CompleteR:
> line   27:
> E15: Invalid expression: flines
> Press ENTER or type command to continue

and in *R*

> VimCom Received: [118] vim.bol("/var/folders/bw/nkfnd3z91yd5cn68x12fd8dw0000gp/T/r-plugin-jomuller/GlobalEnvList_UsersjomullerDesktoptestRvJbt5ONz4wiDVCbDP1b79Q")
> Error [vimcom]: Invalid message received: vim.bol("/var/folders/bw/nkfnd3z91yd5cn68x12fd8dw0000gp/T/r-plugin-jomuller/GlobalEnvList_UsersjomullerDesktoptestRvJbt5ONz4wiDVCbDP1b79Q")

The temp file `GlobalEnvList_UsersjomullerDesktoptestRvJbt5ONz4wiDVCbDP1b79Q` contain

> .GlobalEnv | Libraries
>
>   {#x	

## What I expected ?

To complete my word, in this case to complete `summ` by `summary`.

## Some clues

It worked when I used the stable version of the Vim-R-plugin. I made some changes in the code of the vim-r-plugin then should be my fault. 

The error seems to be in `autoload/rcomplete.vim` and arround the `g:rplugin_liblist` value. I used the `ack` command to find `rplugin_liblist` in the plugin without any results. I will explore it further later.

I tried it also with MacVim and in a tmux session and have the same error.

I tried with the stable version of the plugin from https://github.com/vim-scripts/Vim-R-plugin and I have still the bug. Then I should be an error in my configuration.

**Comment by jalvesaq** [comment]
The variable `g:rplugin_liblist` does not exist in the development version. Maybe there are some files from version 1.2 in your `.vim` directory.

**Comment by jomuller** [comment]
That's it! I had the file `~/.vim/autoload/rcomplete.vim` from a previous installation. Sorry for this, I still quite new in the vim's world.
Thank you!
