### ISSUE TITLE
setwd() is not performed at first start of R.app with MacVim, if X11.app is not already started

### ISSUE THREAD

**Issue by jomuller** [jcfaria/Vim-R-plugin#156]
## What I did ?

I opened the file `/Users/jomuller/Desktop/test.R` with _MacVim_. Then I started the _R.app_  with <kbd>local leader</kbd> + <kbd>r</kbd> + <kbd>f</kbd>.

## What append ?

The R session start slowly because the _X11.app_ is launched. The working directory is not set.

> getwd()
> [1] "/Users/jomuller"

If I close _R.app_ with <kbd>local leader</kbd> + <kbd>r</kbd> + <kbd>m</kbd> and relaunch it (with _X11.app_ already started_), it work perfectly.

## What I expect?

The R session started with my Vim working directory as R working directory the first time I launch R.

In this case 

> getwd()
> [1] "/Users/jomuller/Desktop"

### Config

- I'm using actual dev version of vim-r-plugin, including the fixes of bug #152 .
- _MacVim_ Snapshot 73
- _R_ version 3.1.2 (2014-10-31)
- OS X 10.10.2
- My global config is a mess, because I did a lot of install/uninstall/reinstall without any clean install of my system since 2 years. Then maybe the fault is mine.

### Verbose

When I start for the first time, without _X11.app_ already started, the vimcom (=4) verbose messages are:

> vimcom: R started by MacVim (servername = VIM).
> vimcom: VIMEDITOR_SVRNM=MacVim_VIM
> vimcom port: 10001
> [R.app GUI 1.65 (6833) x86_64-apple-darwin13.4.0]
> 
> VimCom Received: [5] B Update OB [StartR]
> [Espace de Travail restauré depuis /Users/jomuller/.RData]
> [Historique recherché depuis /Users/jomuller/.Rapp.history]
> 
> 2015-02-10 09:42:13.270 R[1767:38710] Antidote - Texteurs: Module texteur installé dans /Applications/R.app (org.R-project.R)
> Time to Update the Object Browser: 0.000029 + 0.000220
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('stats')'
> vimcom R: No need to build omnils: stats 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('graphics')'
> vimcom R: No need to build omnils: graphics 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('grDevices')'
> vimcom R: No need to build omnils: grDevices 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('utils')'
> vimcom R: No need to build omnils: utils 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('datasets')'
> vimcom R: No need to build omnils: datasets 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('vimcom')'
> vimcom R: No need to build omnils: vimcom 1.2-0.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('setwidth')'
> vimcom R: No need to build omnils: setwidth 1.0-3 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('methods')'
> vimcom R: No need to build omnils: methods 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('base')'
> vimcom R: No need to build omnils: base 3.1.2 
> VimCom Received: [8] UsersjomullerDesktoptestRAW3GvqmZRdCRp0FWt3OO9wsetwd("/Users/jomuller/Desktop")

### With X11 already started 

- I don't have this bug when _X11.app_ is already started my working directory is for example `~/Desktop`

> vimcom: R started by MacVim (servername = VIM).
> vimcom: VIMEDITOR_SVRNM=MacVim_VIM
> vimcom port: 10001
> VimCom Received: [5] B Update OB [StartR]
> [R.app GUI 1.65 (6833) x86_64-apple-darwin13.4.0]
> 
> [Espace de Travail restauré depuis /Users/jomuller/.RData]
> [Historique recherché depuis /Users/jomuller/.Rapp.history]
> 
> VimCom Received: [8] UsersjomullerDesktoptestR1FQAcifvxveTyn4KZiITuAsetwd("/Users/jomuller/Desktop")
> 2015-02-10 09:30:15.558 R[1096:34258] Antidote - Texteurs: Module texteur installé dans /Applications/R.app (org.R-project.R)
> vimcom_eval_expr: 'setwd("/Users/jomuller/Desktop")'
> Time to Update the Object Browser: 0.000018 + 0.000079
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('stats')'
> vimcom R: No need to build omnils: stats 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('graphics')'
> vimcom R: No need to build omnils: graphics 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('grDevices')'
> vimcom R: No need to build omnils: grDevices 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('utils')'
> vimcom R: No need to build omnils: utils 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('datasets')'
> vimcom R: No need to build omnils: datasets 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('vimcom')'
> vimcom R: No need to build omnils: vimcom 1.2-0.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('setwidth')'
> vimcom R: No need to build omnils: setwidth 1.0-3 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('methods')'
> vimcom R: No need to build omnils: methods 3.1.2 
> vimcom_eval_expr: 'vimcom:::vim.buildomnils('base')'
> vimcom R: No need to build omnils: base 3.1.2 

In this case, we can see that

1. the VimCom call is done before the `vim.buildomnils` functions
2. The expression `vimcom_eval_expr: 'setwd("/Users/jomuller/Desktop")'` is properly sended

### With _Vim_ in terminal

- I don't have this bug if I start _Vim_ in a terminal, close _X11.app_ that is starting always with _Vim_ and then start _R.app_ (which start again _X11.app_).
- I tried also the same experience in a _tmux_ session without any problem.

## Questions

- Why _vim-r-plugin_ need _X11.app_? _R.app_ can be used without _X11.app_ started.
- Why when I start _Vim_ in a terminal, It always start also _X11.app_ ? (not the case with _MacVim_). Then I don't have this bug with a _tmux_ session, because _X11.app_ is always opened when _Vim_ is.

I will explore this bug deeper this week-end.
Thank you again for this plugin!

**Comment by jalvesaq** [comment]
> Why when I start Vim in a terminal, It always start also X11.app ?

See: [Starting the Display Server].

Does `vim` starts the X11.app when also when called without the `--servername` argument?

> Why when I start Vim in a terminal, It always start also X11.app ?

I am no sure whether Mac OS X automatically starts X11.app when you start an application that is *linked* to X11 (even if the application actually never calls any X11 function) or if it starts X11.app only if an X11 function is called. If it is started only when an X11 function is *called*, then this change may fix the problem: https://github.com/jalvesaq/VimCom/commit/956e26442707156c376d35e2bb2c749a81f33d0e

[Starting the Display Server]: http://www.finkproject.org/doc/x11/x11.en.html#run-xfree86.display-server

**Comment by jalvesaq** [comment]
I think that this is solved by https://github.com/jcfaria/Vim-R-plugin/commit/4c005db88e0b6c28e0ad7b4cc00a0bf0ef34a8de

**Comment by jalvesaq** [comment]
The bug is fixed now: https://github.com/jcfaria/Vim-R-plugin/issues/167#issuecomment-90559004

**Comment by jomuller** [comment]
I confirm that this bug is gone. Thank you very much!
