### ISSUE TITLE
`source(..., local=true)` 

### ISSUE THREAD

**Issue by brandonwillard** [jcfaria/Vim-R-plugin#159]
Is it possible to set the `local` option in the `source` call (i.e. `source(..., local=true)`) when sending selected text?

**Comment by jalvesaq** [comment]
It was not possible, but now it is: https://github.com/jcfaria/Vim-R-plugin/commit/9dbc1f43dbe6fe0c6bbd683f92eb3337a05d2b61. Please, put in your *vimrc*:

```vim
let vimrplugin_source_args = "local = TRUE"
```

This will affect not only sending selected text, but also marked blocks, paragraphs, functions, and the entire buffer.

**Comment by brandonwillard** [comment]
Great!  Many thanks.

**Comment by jalvesaq** [comment]
You are welcome!
