### ISSUE TITLE
Add command to read code function to vim

### ISSUE THREAD

**Issue by hcraT** [jcfaria/Vim-R-plugin#161]
Hi,
first of all I would like to thank you for this plugin.

I find often useful to print a function code by typing a function name in the R repl. I'm wondering if it would be possible to add a command that opens a buffer in vim with the code of that function.

Hope it is clear.

Thanks.

**Comment by jalvesaq** [comment]
You can use  `:Rinsert`. You can even press `<Tab>` to complete the name of the function. For example, to get the code of `read.table()` in Normal mode, type:

```
tabnew newfile.R
:Rinsert read.t<Tab>
```

You can also jump to R source code as explained at `:h r-plugin-tagsfile`

**Comment by hcraT** [comment]
Thanks.

Sorry for the noise.

**Comment by jalvesaq** [comment]
You are welcome!
