### ISSUE TITLE
Send and echo code shortcuts

### ISSUE THREAD

**Issue by enrico16** [jcfaria/Vim-R-plugin#162]
I noticed the various send and echo code shortcuts (e.g.: `\ae`, `\pe`, `\se`) were removed.
I used to use them all the time and found them invaluable, especially for debugging because I can immediately understand at what stage errors occur.

Is it possible to have them back, please?

Thanks!

**Comment by jalvesaq** [comment]
If you always want the `source()` command with the argument `echo=TRUE`, you should put in your *vimrc*:

```vim
let vimrplugin_source_args = "echo = TRUE"
```

If you want to alternate the `echo` argument between `TRUE` and `FALSE`, then, you might want to create a couple of maps in your *vimrc*. You can use `nmap` to restrict the maps to Normal mode, `autocmd` and `<buffer>` to restrict the maps to R code, and `<silent>` if you prefer that the command is not displayed in Vim's command line. In the example below, `<LocalLeader>ee` sets `echo=TRUE` and `<LocalLeader>ne` sets `echo=FALSE`:

```vim
autocmd BufNewFile,BufRead *.R* nmap <silent><buffer> <LocalLeader>ee :let vimrplugin_source_args = "echo = TRUE"<CR>
autocmd BufNewFile,BufRead *.R* nmap <silent><buffer> <LocalLeader>ne :let vimrplugin_source_args = "echo = FALSE"<CR>
```

If some of your files are named with lowercase "r"  extensions, you have to repeat the two commands with `*.r*`.

**Comment by enrico16** [comment]
Great, thanks!
