### ISSUE TITLE
Slow start and vimcom fails

### ISSUE THREAD

**Issue by enrico16** [jcfaria/Vim-R-plugin#165]
Hi,

I've recently upgraded both dev versions of Vim-R-plugin and VimCom and I noticed these two issues:

- When I open a .R file with `vim --servername VIM`, it takes vim a long time to load and display the file (~ 5 seconds).
- When I start R from vim (through tmux) vimcom fails to load and I get this message:
```
vimcom: Did you pass the --servername argument to Vim?
             Please, in Vim, enter Normal mode and type:
             :h r-plugin-nox
vimcom: vimremote_init() failed.
```

Can you please help me understand what's wrong and how I can fix it?
Many thanks,

**Comment by jalvesaq** [comment]
These two links are helpful to understand the issue:

http://www.lepem.ufc.br/jaa/r-plugin.html#r-plugin-nox
http://www.lepem.ufc.br/jaa/vimrcom.pdf

Please, look at the output of  `:version`. Does your vim has the 'clientserver' feature?

**Comment by enrico16** [comment]
I have vim 7.4 compiled with the clientserver feature and aliased to `vim --servername VIM`:

```bash
$ vim --version | grep clientserver
+clientserver    -hangul_input    +netbeans_intg   +title
$ alias vim
alias vim='vim --servername VIM'
```
Also, it used to work fine before.
Anything I can do?

**Comment by jalvesaq** [comment]
What is your operating system?  If it is OS X, then, the X Server might be started by Vim and that would explain the 5 seconds to start Vim, but not to load a .R file.

What is the output in Normal mode Vim of:  `:echo v:servername`? Because you started vim with the argument `--servername VIM`, the output should be `VIM`.

**Comment by enrico16** [comment]
Thanks for pointing me to the right direction (i.e.: checking the servername from inside vim).
In short, it was a ssh X11 forwarding issue caused by a recent Cygwin upgrade.
Using `DISPLAY=:2.0` in my Cygwin .bashrc solved the connection issue.
