### ISSUE TITLE
Working directory not set on Mac OS

### ISSUE THREAD

**Issue by songcai** [jcfaria/Vim-R-plugin#167]
I am using MacVim to call Vim-R-plugin (version 1.2.2) on Mac OS X 10.10.2. The terminal of my choice is the Mac built-in Termianl.app. When I invoke R in Termianl (without X), the working directory is always my home directory regardless where the file is. I tried to set "let vimrplugin_vim_wd=1" in .vimrc, but got the same result: the working directory in R is still my home directory.

Is this the supposed behavior on OS X? Is there a way that I can set the startup working directory in R to the directory where my file is?

Many thanks.

**Comment by jalvesaq** [comment]
The value of `vimrplugin_vim_wd` should be `0`, which is the default if you do not change it in your *vimrc*.

I no longer have access to Mac OS X, but I can try to solve the problem with your help. It seems that the command to change MacVim working directory (`:lcd`) does not have the effect of starting R in the script directory. As a second attempt, the plugin sends a message to vimcom to `setwd()`. If this is not working, first, we should check if vimcom indeed is receiving the message. Please, put in your *~/.Rprofile*:

```s
options(vimcom.verbose = 4)
library(vimcom)
```

Do you see in the R Console a message like "vimcom received setwd(dir)" during R startup?

**Comment by jalvesaq** [comment]
I have just changed the way that the working directory is set: https://github.com/jcfaria/Vim-R-plugin/commit/4c005db88e0b6c28e0ad7b4cc00a0bf0ef34a8de

But to test if it now works you should use the development versions of Vim-R-plugin and vimcom.

**Comment by songcai** [comment]
Thanks a lot, Jackson!

After setting options(vimcom.verbose = 4) with library(vimcom), I still cannot see anything like ""vimcom received setwd(dir)" during R startup.

However, your new update worked like a charm. With the newest development version, the working directory is correctly set. I still don't see anything like ""vimcom received setwd(dir)" during R startup though, but it does not matter any longer.

Thanks you so much for your hard work. This is indeed a beautiful plugin of Vim.

**Comment by jalvesaq** [comment]
Thanks for the feedback! The message is no longer sent to vimcom. Now, the Vim-R-plugin creates an R script that vimcom sources when it is being loaded.
