### ISSUE TITLE
Vim should not wait for either \ao or \so to finish

### ISSUE THREAD

**Issue by jalvesaq** [jcfaria/Vim-R-plugin#173]
When running `<LocalLeader>ao`, Vim waits until the job is finished. When running `<LocalLeader>so`, Vim waits only two seconds for the conclusion of the job. In both cases, instead of waiting, it should allow users to keep editing the code while the job was running, and put the result in a new tab without disturbing the user workflow.

See: https://github.com/jcfaria/Vim-R-plugin/issues/170#issuecomment-97727041

**Comment by jalvesaq** [comment]
I implemented the change in a new branch: https://github.com/jcfaria/Vim-R-plugin/tree/dont_wait_output
However Vim cannot open a new tab without changing the focus to it, that is, we cannot create a buffer and change its contents without going there. With the changes made in the new branch, the new tab is created and the cursor immediately goes back to the original tab, but, if you are typing quickly when this happens, at least one character may be in the wrong place (it will be put in front instead of behind the cursor).

I'm waiting for comments. A couple of things to consider:

  - Is this new behavior better, in spite of the issue described above, or is it better to wait for the output because the waiting may be annoying but is bug free?

  - If the output is produced very quickly (for example, in less than 0.1 second) the focus should go to the new tab or the focus must always remain the original buffer?

Those who want to test the branch can do:

```
git fetch origin dont_wait_output:dont_wait_output
git checkout dont_wait_output
```

**Comment by scheike** [comment]
Tried it out right away, and it works pretty ok, seems however that there are some differences:

when the output gets back right away I can navigate around tabs with :bn

when I wait and leave the visual mode and start editing something else while waiting then I can not go to the tab when it shows up with :bn,

could tabs be named so1 , so2  or whatever 

I think it is a very useful feature that I would use

**Comment by jalvesaq** [comment]
The problem to navigate between tabs using `:bn` may be related with the Vim limitation that I described in the second comment to this issue. In Normal mode, you can do `gt` to go to next tab, `gT` to go to the previous tab, `{count}gt` to go to a specific tab.

The tabs now are named so1, so2, ... I suppose that you would not save them with these names, so I did:

```vim
setlocal buftype=nofile
setlocal noswapfile
```

**Comment by scheike** [comment]
nice works very nicely, will start using this in more normal workflow and report any problems,

**Comment by jalvesaq** [comment]
I merged the code into the master branch... If anyone find any problem, we can reopen the issue.
