### ISSUE TITLE
Win XP general errors

### ISSUE THREAD

**Issue by lrsilveira** [jcfaria/Vim-R-plugin#174]
R version: 3.2.0 (2015-04-16)
Vim version: 7.4 (I'm using GVim)
vimcom: 1.2-5

All things according site instructions.

---------------------------------------
If I try install the vimcom from source in R, I get some errors:
>download.file("http://www.lepem.ufc.br/jaa/vimr/vimcom_1.2-5.tar.gz", destfile = "vimcom_1.2-5.tar.gz")
trying URL 'http://www.lepem.ufc.br/jaa/vimr/vimcom_1.2-5.tar.gz'
Content type 'application/x-gzip' length 72311 bytes (70 KB)
downloaded 70 KB

>install.packages("vimcom_1.2-5.tar.gz", type = "source", repos = NULL)
Error in library(vimcom) : there is no package called 'vimcom'
Execution halted
Warning messages:
1: running command '"C:/ARQUIV~1/R/R-32~1.0/bin/i386/R" CMD INSTALL -l "C:\Arquivos de programas\R\R-3.2.0\library" "vimcom_1.2-5.tar.gz"' had status 1 
2: In install.packages("vimcom_1.2-5.tar.gz", type = "source", repos = NULL) :
  installation of package ‘vimcom_1.2-5.tar.gz’ had non-zero exit status

--------------------------------------------

But the option from binary its ok.

>download.file("http://www.lepem.ufc.br/jaa/vimr/vimcom_1.2-5.zip", destfile = "vimcom_1.2-5.zip")
>install.packages("vimcom_1.2-5.zip", type = "win.binary", repos = NULL)

Its run ok.

After that, if I open a .R script, I get several error messages, starting with:

-------------------------------
>Could not determine user name. [Press <enter> to continue]

>Error detected while processing C:\Arquivos de programas\Vim\vimfiles\r-plugin\common_global.vim:
line 3046:
E121: Undefined variable: g:rplugin_userlogin
E15: Invalid expression: $TMP . "/r-plugin-" . g:rplugin_userlogin
line 3068:
E121: Undefined variable: g:rplugin_tmpdir
E15: Invalid expression: g:rplugin_tmpdir
line 3069:
>E121: Undefined variable....

etc
Several errors

------------------------------

I don't know how I fix it. Any suggestion?

**Comment by jalvesaq** [comment]
To install vimcom from source, you have to install [Rtools](http://cran.r-project.org/bin/windows/Rtools/) first, and you also have to set your PATH environment variable...

I guess it's not a good idea to install the plugin in `C:\Arquivos de programas`. Did you install the Vimball from [vim.org](http://www.vim.org/scripts/script.php?script_id=2628)?

The plugin makes two attempts of finding the user name:

  1. Run the application `whoami`.
  2. Get the value of the environment variable `USER`.

What is the result in GVim of the following commands:

```vim
:echo $USER
:echo $USERNAME
```

Perhaps I should add a third way of trying to find the user name (checking `$USERNAME`).

**Comment by jalvesaq** [comment]
Any news about the problem? I suppose that there was something wrong with your installation...

**Comment by lrsilveira** [comment]
In win XP did not work, I tried everything and it failed. I tried to install again, but without success. The OS seems unstable, I will install win 7 on that PC.

On another PC with win 7 the plugin work.  I installed compiling vimcom and it worked. Although it works, every time I open an R script in Vim, it returns the message: "Your runtime files seems to be outdated. See: https://github.com/jalvesaq/R-Vim-runtime"

Another question: how to use the auto-completion? I need an example to know how it works. I tried keystrokes and nothing happens...

**Comment by jalvesaq** [comment]
Although currently I can only test the plugin on Windows 8, the code that find the user name was developed many years ago on Windows XP. That's why I think there is something wrong with your system.

Regarding the runtime files, you have two options: (1) copy the directories `ftplugin`, `indent` and `syntax` to `~/vimfiles`; (2) install a newer version of GVim (see http://www.vim.org/download.php#cream and get "vim without cream", http://sourceforge.net/projects/cream/files/Vim/).

To test the omnicompletion, write `read.` and, still in insert mode, press `<c-x><c-o>`, that is, hold the key `Ctrl` and quickly press the keys `x` and `o`. But it may not work if you have not solved the other problems.

**Comment by lrsilveira** [comment]
I copied the directories ftplugin, indent and syntax to /vimfiles, and it works!
In option 2, I did not understand what file download... The version of my GVim was already the newest.
The omnicompletion also works fine.

**Comment by jalvesaq** [comment]
The newest version of GVim on vim.org is from August, 2013, but if it works for you, then, you don't need to worry about updating it. If you still want to update it, you should download a new version from http://sourceforge.net/projects/cream/files/Vim/

**Comment by lrsilveira** [comment]
Thanks, actually I did not know how are the versions of VIM for windows. I think it was just this official...

**Comment by jalvesaq** [comment]
New versions of Vim are officially released only after 2 to 3 years of development, but most of the support for R that is part of the official distribution was included after 2013.

Cream is Vim modified, but the Cream developers also release a binary version of Vim without the modifications that is only a few days behind the current development version of Vim.
