### ISSUE TITLE
can not locate vimcom dll on windows 8

### ISSUE THREAD

**Issue by bdcaf** [jcfaria/Vim-R-plugin#175]
I use 64-bit R on windows and did get an error about not finding the dll in the bin/i386 directory.
 I could narrow it down to the file common_global.vim lines 987 and on. On my machine both has("win32") and has("win64") evaluate to true - which seems to be convention. I was able to quickly fix it for myself by changing the order of these comparisons - but I don't have enough insight to suggest this as fix.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug, and how to fix it. I only tested the plugin on Windows with the official GVim, which is 32 bit. I knew that has("win32") is always true, and has("win64") is true only if GVim is 64bit, but I did a mistake in the code.
