### ISSUE TITLE
Roxygen examples section: highlight and execute R code

### ISSUE THREAD

**Issue by jranke** [jcfaria/Vim-R-plugin#176]
It would be great if code in a Roxygen example section like

```
#' @examples
#' H_sw_D4_pond  <- read.TOXSWA_cwa("00001p_pa.cwa",
#'                                  basedir = "SwashProjects/project_H_sw/TOXSWA",
#'                                  zipfile = system.file("testdata/SwashProjects.zip",
#'                                              package = "pfm"))
```

would be highlighted and could be sent to R.

**Comment by jalvesaq** [comment]
Could you do a pull request to [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) adding the recognition of ROxygen example region in `syntax/r.vim`? Perhaps the highlighting should be optional since I guess that some people will prefer the whole Oxygen documentation highlighted as `Comment`.

I created a branch where we can develop the code to send the ROxygen lines: [send_roxygen_lines](https://github.com/jcfaria/Vim-R-plugin/tree/send_roxygen_lines). In this branch, lines are striped from `^#'` and, then, can be sent to R, but perhaps we could add a restriction to only send lines that are in an example section.

**Comment by jranke** [comment]
Sounds good. It may take me a while, as I am under pressure at the moment, and 
I haven't edited a vim syntax file since years...

Johannes

**Comment by jranke** [comment]
OK, have a look at jalvesaq/R-Vim-runtime#2. At the moment, the roxygen lines with example code are highlighted as SpecialComment.

**Comment by jalvesaq** [comment]
@jranke Should the send_roxygen_lines branch be merged into the master branch?

**Comment by jranke** [comment]
We now have rOExamples as a syntax element in R-vim-runtime - can we use that for doing the substitution only for lines that are actually part of examples? Also, the syntax file now also supports `##'` as a roxygen comment, in addition to `#'`, so it would be great if the substitution could also take care of that.

**Comment by jalvesaq** [comment]
Since I don't use ROxygen, and you know VimLanguage, could you please write a pull request combining the changes made in the `send_roxygen_lines` branch with your new suggestions? I would then merge the pull request and delete the branch.

**Comment by jranke** [comment]
I understand. I think you overestimate my abilities in the vim language... I did look at the code in common_global.vim but I am far from understanding it. I now also tried to modify the modifications you made to also substitute ##':

https://github.com/jcfaria/Vim-R-plugin/compare/master...jranke:send_roxygen_lines

but it does not work as expected.

**Comment by jranke** [comment]
My workaround is to put example code into inst/examples/xxx.R and use the roxygen tag

```
#' @examples inst/examples/xxx.R
```

This has the nice consequence that example code can be sourced in tests.

**Comment by jalvesaq** [comment]
And I don't know how to work with branches in git... But I will try later.

**Comment by jalvesaq** [comment]
I did the changes in old send_roxygen_lines branch and then I created a new branch: https://github.com/jcfaria/Vim-R-plugin/tree/send_roxygen_lines2

I believe that both branches are equivalent. @jranke If you think that the new branch is OK I will merge it.

**Comment by jranke** [comment]
Wow, this works nicely indeed! Great work. Yes, I think this should be merged and the issue closed.

**Comment by jalvesaq** [comment]
Done: https://github.com/jcfaria/Vim-R-plugin/commit/136738faad9966079e3c05c140845ed594299c25

**Comment by pnth** [comment]
Could you please add an option to disable roxygen highlight as you mentioned on Jun 12. I put the following in .vimrc
```vim
 let g:r_hl_roxygen = 1 
```
and in syntax/r.vim
```vim
" Roxygen
if exists("g:r_hl_roxygen")
  syn region rOBlock start="^\s*\n#\{1,2}' " start="\%^#\{1,2}' " end="^\(#\{1,2}'\)\@!" contains=rOTitle,rOKeyword,rOExamples,@Spel
l keepend
  syn region rOTitle start="^\s*\n#\{1,2}' " start="\%^#\{1,2}' " end="^\(#\{1,2}'\s*$\)\@=" contained contains=rOCommentKey
  syn match rOCommentKey "#\{1,2}'" containedin=rOTitle contained

  syn region rOExamples start="^#\{1,2}' @examples.*"rs=e+1,hs=e+1 end="^\(#\{1,2}' @.*\)\@=" end="^\(#\{1,2}'\)\@!" contained conta
ins=rOKeyword

  syn match rOKeyword contained "@\(param\|return\|name\|rdname\|examples\|example\|include\|docType\)"
  syn match rOKeyword contained "@\(S3method\|TODO\|aliases\|alias\|assignee\|author\|callGraphDepth\|callGraph\)"
  syn match rOKeyword contained "@\(callGraphPrimitives\|concept\|exportClass\|exportMethod\|exportPattern\|export\|formals\)"
  syn match rOKeyword contained "@\(format\|importClassesFrom\|importFrom\|importMethodsFrom\|import\|keywords\|useDynLib\)"
  syn match rOKeyword contained "@\(method\|noRd\|note\|references\|seealso\|setClass\|slot\|source\|title\|usage\)"
  syn match rOKeyword contained "@\(family\|template\|templateVar\|description\|details\|inheritParams\|field\)"
endif
```
Many thanks

**Comment by jalvesaq** [comment]
Thanks for remembering me of that. It is done now, but with `1` as default value: https://github.com/jalvesaq/R-Vim-runtime/commit/793a822385278f805977ddc8a9d84993016a2801
