### ISSUE TITLE
RMakePDFK doesn't consider if $out_dir of latexmk is set

### ISSUE THREAD

**Issue by nichtleiter** [jcfaria/Vim-R-plugin#177]
Hi,
i don't like to have all output files in my working directory that are written by a latex run. Therefore i have the line
```
$out_dir = 'compiled'
```
in my `.latexmkrc` file. 

If i compile my `rnoweb` files with `<Plug>RMakePDFK` it seems that only the working directory is considered and i get the following messages
```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file 'doc.log': No such file or directory
````

It would be great if `RMakePDFK` would also consider `$out_dir` to access the necessary files. For the moment it would suffice to have a global variable `g:vimrplugin_latexmk_build_dir` that corresponds to `$out_dir` and which is processed by `RMakePDFK`.

Best regards

**Comment by jalvesaq** [comment]
Can't you solve this with `vimrplugin_latexcmd`?

**Comment by jalvesaq** [comment]
@nichtleiter Please, reopen the issue if you can't solve the problem with `vimrplugin_latexcmd`. I don't use latexmk in the same way that you use, hence I don't know the answer to my question in the last comment.
