### ISSUE TITLE
undefined variable: g:rplugin_vimcom_lib erorr without admin?

### ISSUE THREAD

**Issue by jpmorris** [jcfaria/Vim-R-plugin#178]
I don't have admin privileges, but I install to windows 7 as per instructions using gvim (64bit), an R 3.2.1 64bit. It seems no matter what I do I get this error:

    Error detected while processing function SendFileToR..SendCmdToR_Windows: 
    line   11:
    E121: Undefined variable: g:rplugin_vimcom_lib
    E116: Invalid arguments for function libcall(g:rplugin_vimcom_lib, "SendToRConsole", cmd)
    E15: Invalid expression: libcall(g:rplugin_vimcom_lib, "SendToRConsole", cmd)
    line   13:
    E121: Undefined variable: repl
    E15: Invalid expression: repl != "OK"

I did modivy my Rprofile file and my _vimrc has:

    set nocompatible
    syntax enable
    filetype plugin on
    filetype indent on
    let vimrplugin_r_path = "C:\\Users\\mor\\progs2\\R\\R-3.2.1\\bin\\x64"

vimrplugin_r_path is necessary because I assume I don't have admin access and therefore this info isn't in the registry

**Comment by jalvesaq** [comment]
Did not you get any error message before the above one? Was not there any error message during R startup?

What is the output in Vim of the following commands?

```vim
:echo g:rplugin_vimcom_home
:echo g:rplugin_vimcom_lib
```

**Comment by jpmorris** [comment]
No I did not get any messages.  R loaded fine with \rf

    :echo g:rplugin_vimcom_home
    
    :echo g:rplugin_vimcom_lib
    E121: Undefined variable: g:rplugin_vimcom_lib
    E15: Invalid expression: g:rplugin_vimcom_lib

**Comment by jalvesaq** [comment]
The output means that the vimcom package was not loaded. But, then, you should have seen the message `The package vimcom wasn't loaded yet`. Did you put `library(vimcom)` in your .Rprofile? Please, check in R if vimcom is loaded: `search()`.

**Comment by jpmorris** [comment]
Thanks so much for your help.  It turns out that my .Rprofile file needed to be placed in my <user folder>/Documents  (as determined by path.expand("~")).  After placing the file there, it seems to work now. Thank you.

**Comment by jalvesaq** [comment]
For Gvim, the user folder is `~`, but for R it is `~/Documents`.
