### ISSUE TITLE
Syntax highlighting fails for R code nested inside formula

### ISSUE THREAD

**Issue by klmr** [jcfaria/Vim-R-plugin#180]
Consider the following code:

![Some text, where $p = `r data$p`$.](http://i.imgur.com/p3KSr6q.png)

Everything that comes after the `$` inside the inline R code is wrongly formatted; the lexer doesn’t seem to consider nested blocks here. and instead scans ahead until it finds the first `$`.

**Comment by jalvesaq** [comment]
The same problem happens with Rnoweb files. The syntax region `texMathZoneX` interprets any `$` as the end of the region, unless it is preceded by a backslash. I have tried to redefine `texMathZoneX` as

```vim
syn region texMathZoneX	matchgroup=Delimiter start="\$" skip="\\\\\|\\\$\|`.*`"	matchgroup=Delimiter	end="\$"	end="%stopzone\>"		contains=@texMathZoneGroup
```
but adding "\`.*\`" to the skip directive did not solve the problem.

My personal workaround for this is to define an R object beforehand to avoid any code that contains a `$` symbol. Example:

```
<<avoidSyntaxError>>
pvalue <- sprintf("%.2f", data$p)
@

Some thext where $p = \Sexpr{pvalue}$
```

**Comment by klmr** [comment]
I know next to nothing of Vim syntax rules but I think the only way to solve this is to define rules for nesting — i.e. define that a math group may contain an R code group.

**Comment by jalvesaq** [comment]
Sorry, but I don't know how to fix the bug. We may leave the issue open until someone finds a solution.
