### ISSUE TITLE
Adding another Rmd output format: tufte_handout style

### ISSUE THREAD

**Issue by samkimhis** [jcfaria/Vim-R-plugin#183]
When I tried to use tufte_handout template (`output: rmarkdown::tufte_handout` in the header), the plugin gives error seemingly because the `\kp` command sends `outform = "pdf_document"`. It will be handy if the content of the `output` argument can be passed onto the `vim.interlace.rmd` function.

**Comment by jalvesaq** [comment]
I can add an option for this. The name of the option could be `vimrplugin_rmd_outform`, and its documentation wold be:

```
By default, the command <LocalLeader>kp runs rmarkdown::render() with the
argument output_format="pdf_document". If you need something different, put
in your vimrc:

   let vimrplugin_rmd_outform = "something_else"
```

Is this new option what you are requesting? Is the proposed documentation clear?

**Comment by samkimhis** [comment]
Yes, that option will work for me.

Alternatively, I was thinking of extracting the output format from the
metadata section. Is this possible? I think it will be simpler, at least
from the user's side, and may prevent conflicting format specifications.

I plan to study your code to contribute to this project! 8-)

**Comment by samkimhis** [comment]
Never mind, the command `\kr` (default) does exactly what I wanted already.

I appreciate your effort into this plugin. It's been very useful for my R projects.

**Comment by mdlerch** [comment]
There is also `RMakeRmd` with default keybinding \kr that just calls (essentially) `rmarkdown::render("file")` so whatever you put in YAML is the output type.

**Comment by mdlerch** [comment]
I'm too slow!

**Comment by samkimhis** [comment]
I guess we posted simultaneously. Thanks!

**Comment by jalvesaq** [comment]
So, is the problem solved?

**Comment by samkimhis** [comment]
Yes, absolutely.

**Comment by jalvesaq** [comment]
Thanks @mdlerch for pointing to the solution, and @samkimhis for the feedback.
