### ISSUE TITLE
\aa \ae and echo

### ISSUE THREAD

**Issue by enrico16** [jcfaria/Vim-R-plugin#184]
I set let vimrplugin_source_args = "echo = TRUE" in my ~/.vimrc and I can see commands echoed when using \pp or \ss.
However \aa does not echo anything. \ae still echoes but I though it had been deprecated?

What can I do to make \aa echo commands like \pp and \ss?

Thanks,

**Comment by jalvesaq** [comment]
You can use \ae. I removed all echo commands on version 1.2.1 (2015-03-05), but some people complained and I brought them back on 1.2.5 (2015-05-06).

**Comment by enrico16** [comment]
I see, but why does \aa not behave like \pp and \ss? Since i've set
    let vimrplugin_source_args = "echo = TRUE"
I would excpect \aa to echo as well.
Otherwise the behaviour is pretty inconsistent and unpredictable.
Thanks,

**Comment by jalvesaq** [comment]
You were right. Please, see the last commit.

**Comment by enrico16** [comment]
Great!
