### ISSUE TITLE
vim-r & vim-markdown Rmd syntax highlighting no longer working

### ISSUE THREAD

**Issue by khughitt** [jcfaria/Vim-R-plugin#186]
Starting sometime in the past couple weeks, syntax highlighting is no longer working properly for .Rmd files when both the vim-r and vim-markdown plugins are used together.

I checked the commit log for https://github.com/plasticboy/vim-markdown but did not notice any obvious ways in which this could have been caused, but I could easily be missing something.

Before:

![2015-10-01-080205_976x418_scrot](https://cloud.githubusercontent.com/assets/125001/10220271/f162b462-6813-11e5-93a0-7722f986c5bc.png)

After:

![2015-10-01-080248_956x422_scrot](https://cloud.githubusercontent.com/assets/125001/10220274/f3fe5230-6813-11e5-9336-b10e0993079e.png)

I disabled all other plugins (except Pathogen), and was able to isolate the issue to something in either vim-r or vim-markdown.

Disabling vim-markdown fixes the issue.

vim version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 10 2015 04:51:12)
Included patches: 1-854
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib
```

**Comment by khughitt** [comment]
@plasticboy - This may be relevant for vim-markdown as well.

**Comment by khughitt** [comment]
More version info:

vim-markdown: 5ff124014066ba7882617c283e7750d449caafb4
vim-r: 443813f0f2f2101bb8bfac1adc1b1fa2e3b2daf1

**Comment by mnosefish** [comment]
I do not have vim-markdown, and this affects me as well.

**Comment by jalvesaq** [comment]
I am sorry, but I can't reproduce the bug. The syntax highlight of Rmd files is normal to me.

**Comment by khughitt** [comment]
Hmm. Vim was also [recently updated](https://projects.archlinux.org/svntogit/packages.git/log/trunk?h=packages/vim) on my system from 7.4.854 -> 7.4.884. Didn't see anything in the changelog (ftp://ftp.vim.org/pub/vim/patches/7.4/README) that seems like it could cause the issue.

Which version of vim are you testing with out of curiosity?

**Comment by jranke** [comment]
@mnosefish - I do not use vim-markdown and here it works fine. I did notice that in markdown I had to use 

```
```{r}
```

instead of 

```
```r
```

or 

```
```{s}
```

to have code highlighting.

**Comment by jalvesaq** [comment]
Vim now is on github. My version is the last one: 7.4.889.

**Comment by khughitt** [comment]
I just tested the same vim setup with a slightly older version of Vim (7.4.854) and there was no problem. Looks like a bug was introduced between 854 and 884 and (hopefully) fixed along the way to 889.

I'll close the issue for now since it looks likely to be unrelated to vim-r, but I'll keep you posted if issues continue past version 884.

Thanks for looking into it!

**Comment by tinyheero** [comment]
Have the exact same problem with vim-7.4.1016 so I don't think the issue has been fixed...I am using the released vim-r-plugin version 1.2.7.

**Comment by jalvesaq** [comment]
I glanced at vim-markdown code and noted that it includes the syntax of other file types. However, Rmd already does this, but only for R. I guess that whatever vim-markdown is doing, it should do only if `&filetype == "markdown"` or at least `&filetype != "rmd"`. Did you report the bug in vim-markdown?

**Comment by ErickChacon** [comment]
Could any one suggest a workaround to using both plugins without clashing? Like disable vim-markdown only in rmd files?

**Comment by jalvesaq** [comment]
Some notes:

   - Syntax and indent scripts are maintained at https://github.com/jalvesaq/R-Vim-runtime and you should first install it to ensure that your R related runtime files are updated. Issues regarding syntax highlight and indentation should be reported there.

   - In my opinion, https://github.com/vim-pandoc/vim-pandoc-syntax provides a better syntax highlight for markdown than the official syntax/markdown.vim script.

   - Even if this was not a syntax highlighting question, Vim-R-plugin is no longer maintained and you should report bugs and ask questions at https://github.com/jalvesaq/Nvim-R

**Comment by paulrougieux** [comment]
When I activate the vim-markdown plugin on .Rmd files, it messes up with syntax highlight and autocompletion of R code chunks. I guess it is related to the way vim-markdown detects "fenced code blocs".

@jalvesaq 
> I guess that whatever vim-markdown is doing, 
> it should do only if &filetype == "markdown" or at least &filetype != "rmd". 

In fact the only command I want to use from the vim-markdown plugin is the table of content `:Toc` functionality. In R markdown files, I would like to disable all functions related to code chunks but keep the `:Toc` command.  It has been an open issue since 2016: https://github.com/plasticboy/vim-markdown/issues/263
Any hint on how I could describe it properly to the vim-markdown authors? 

Minimal reproducible example:

minimal_no_markdown_toc.vim 
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/Nvim-R,' . &runtimepath
filetype plugin indent on
syntax enable
let maplocalleader = ";"
```


minimal_markdown_toc.vim 
```
set nocompatible
let &runtimepath  = '~/.vim/bundle/Nvim-R,' . &runtimepath
let &runtimepath  = '~/.vim/bundle/vim-markdown,' . &runtimepath
filetype plugin indent on
syntax enable
"
let maplocalleader = ";"

" enable vim-markdown for .Rmd files too
" This might conflict with the Nvim-R plugin
augroup filetypedetect_markdown
    au!
    au BufRead,BufNewFile *.Rmd set ft=rmd.markdown
augroup END
```

minimal.Rmd 

```

    # Test

    ```{r test}
    1+1
    1+1
    ```


    ```{r test2}
    2+1
    ```

```

Starting vim with `vim minimal.Rmd -u minimal_no_markdown_toc.vim` I get syntax highlight and autocomplete on R chunks but no table of content for the markdown titles.

Starting vim with `vim minimal.Rmd -u minimal_markdown_toc.vim` I loose syntax highlight and autocomplete on R chunks but I get a table of content.

**Comment by jalvesaq** [comment]
Vim-R-plugin is no longer maintained. You should report bugs and ask questions at https://github.com/jalvesaq/Nvim-R
