### ISSUE TITLE
omnicompletion not working in .Rmd, .rnw

### ISSUE THREAD

**Issue by mnosefish** [jcfaria/Vim-R-plugin#187]
The title pretty much says it. With .R scripts, <C-x><C-o> works as expected. This is not the case with .Rmd and .rnw--this yields `-- Omni completion (^O^N^P) Pattern not found`. Everything else including argument completion appears to work fine in these filetypes.

**Comment by jalvesaq** [comment]
The omnicompletion works fine here (Ubuntu 15.04, Vim 7.4.889). My test was simple: I created an object named "abc":

```s
abc <- 0
```

Then, I tried the omnicomletion of "ab".

**Comment by mnosefish** [comment]
Version 7.4.854, Arch kernel 4.2.1-1. I tried disabling and all plugins, then removed and reinstalled vim and vim-r. Where should I look to start troubleshooting this?

**Comment by jranke** [comment]
As far as I understand, you have a 
different, more general problem from the 
original reporter, so I would recommend 
to open a new issue and explain exactly 
what you do, what you would expext to 
happen, and what happens.

**Comment by mnosefish** [comment]
Forgive me if I'm being obtuse; this is the first time I've ever done one of these, but I thought this was started as a new issue. Further detail will be forthcoming.

**Comment by jranke** [comment]
Ooops, sorry, yes, this really 
was started as a new issue - 
you are completely right... It 
was only me who mixed it up...

**Comment by mnosefish** [comment]
set filetype=r
 ```{r}
aplus <- function (x) {
       x+1
  }
  ```
apl<C-x><C-o> >>>aplus
added a '('
<C-x><C-a> >>> x =

:set filetype=rmd
apl<C-x><C-o> >>> -- Omni completion (^O^N^P) Pattern not found
aplus( <C-x><C-a> >>> x = 

:set filetype=rnw
apl<C-x><C-o> >>> 'option 'omnifunc' not set
aplus(<C-x><C-a> >>> x = 

Tried removing .vim and .vimrc and installing only vim-r plugin, same results. Reinstalled vimcom.

**Comment by mdlerch** [comment]
I think I am seeing the same thing on nvim.  @mnosefish you can try `:verbose setlocal omnifunc?`.  Perhaps it says `omnifunc=htmlcomplete#CompleteTags` set by `....../runtime/ftplugin/html.vim`?  You can replace the html omnifunction with the Vim-R-plugin omnifunction with `:setlocal omnifunc=CompleteR`.  To make this permanent you could add that command to `~/.vim/after/ftplugin/rmd.vim`.

@jalvesaq `ftplugin/rmd.vim` in R-Vim-runtime sources `ftplugin/html.vim` and others.  On my system, this happens after `R/common_buffer.vim` sets the omnifunc.  Maybe `ftplugin/rmd.vim` in R-Vim-runtime should protect against this?  Or better yet, an omnifunc that uses CompleteR and then reverts to the html completion if no matches are found?

On my system, CompleteR is the omnifunc for rnoweb files.  Which maybe is your problem @mnosefish  for Rnw files?  Try setting the file type to rnoweb not rnw.

**Comment by jalvesaq** [comment]
Following Michael Lerch's suggestion, I generalized a mechanism that was active only for Latex-Box completion. Please, see the last commit.

@mnosefish The sequence that Vim reads the runtime files is not the same in all systems. This may make some bugs difficult to reproduce in other machines. I guess the last commit will not fix the bug that your reported.

**Comment by mnosefish** [comment]
I pulled in the latest from this repo. I had been using the stable version. 
@mdlerch This was indeed the case I ran. `setlocal omnifunc=CompleteR`, however now I receive `Unknown Function: CompleteR`, followed by the pattern not

**Comment by mnosefish** [comment]
I switched the filetype back to r, and ran `verbose setlocal omnifunc?`. The correct function was `rcomplete#CompleteR`. Everything appears to be working now. I'll leave it up to you to determine if you want to pursue this issue further, but I'm happy with this resolution. I'll add that to my ftplugin>>rmd.

**Comment by jalvesaq** [comment]
I believe that this issue is fixed, and I am closing it. If anyone experience something similar, please, reopen this issue or open a new one.
