### ISSUE TITLE
E364: Library call failed for "SendToRConsole()"

### ISSUE THREAD

**Issue by sfr** [jcfaria/Vim-R-plugin#189]
Hi,

I have the following configuration:
Win7x64
R 3.2.2
vim 7.4.827 *currently latest at http://sourceforge.net/projects/cream/files/Vim/*
Vim-R-plugin.vmb 1.2.6 *from http://www.vim.org/scripts/script.php?script_id=2628*

**_vimrc:**
```vim
	set nocompatible
	syntax enable
	filetype plugin on
	filetype indent on
	
	let vimrplugin_r_path = "c:\\Tools\\R-3.2.2\\bin\\x64"
```
**.Rprofile:**
```R
	options(vimcom.verbose=4)
	library(vimcom)
```
**test.R**
```R
	a <- 10.1
	b <- as.integer(2)
	
	d <- c('aa', 'bb', 'cc', 'dd')
	e <- function()
	{
		print('Hello World!')
	}
	
	str(d)
```

I run:
```cmd
	gvim.exe g:\code\test.R
```

then I press **\rf** and it opens R console:
```
		vimcom: VIMEDITOR_SVRNM=GVIM
		vimcom 1.2.6 loaded
		    VIMTMPDIR = c:/TEMP/r-plugin-sfr
		    VIMINSTANCEID = GcodetestR1445530604
		vimcom port: 10001
```
outputting environment variables related to the error line later:
```vim
:echo g:rplugin_vimcom_lib
c:/Tools/R-3.2.2/library/vimcom/bin/i386/libVimR.dll
:echo g:vimrplugin_ca_ck
0
```
then I press **\l** and it gives me this error:
```
Error detected wile processing function SendLineToR..SendCmdToR_windows:
line 11:
E364: Library call failed for "SendToRConsole()"
```

When I update **R-Vim-runtime** and **Vim-R-plugin** to the latest code from github, result is the same.

What did I miss?

Regards,
	Juraj.

**Comment by jalvesaq** [comment]
Everything looks like correct in your configuration.
Do you see any other warning or error messages output by the `:messages` command in Vim?

**Comment by jalvesaq** [comment]
This code is in use since November, 2014. It is strange that it stopped working now. So, maybe there is something wrong (or different) in your system. Having R installed in a non default directory should not cause any problem, but I did not test this scenario. If you let R register itself in Windows registry during the installation, Vim should be able to find it (no need of setting `vimrplugin_r_path`).

**Comment by sfr** [comment]
I'm pretty sure that there is something strange with my setup. But I would love to find out.
I will try later to install all in the default locations.

**Vim log (level 9)**
```
Calling shell to execute: "reg.exe QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v "Personal" >c:\TEMP\VIoDC0.tmp 2>&1"
:!start "c:\Tools\R-3.2.2\bin\x64\Rgui.exe" --sdi

Calling shell to execute: "start "c:\Tools\R-3.2.2\bin\x64\Rgui.exe" --sdi"
Waiting vimcom loading...


Error detected while processing function SendFileToR..SendCmdToR_Windows:
line   11:
E364: Library call failed for "SendToRConsole()"


Writing viminfo file "C:\Users\sfr\_viminfo"
Executing VimLeave Auto commands for "*"
autocommand call RVimLeave()
```

The level 15 log is a bit too verbose for this space.

**Comment by jalvesaq** [comment]
I can't see anything suspect in the log above. If you wanted, you could compress the log of level 15 and send it to me by e-mail.

**Comment by jalvesaq** [comment]
The problem might also be in the file `c:/Tools/R-3.2.2/library/vimcom/bin/i386/libVimR.dll`. In this case, we would not find anything in Vim log.

**Comment by jalvesaq** [comment]
This might be fixed by:
https://github.com/jcfaria/Vim-R-plugin/tree/jobchannel
https://github.com/jalvesaq/VimCom/tree/jobchannel

**Comment by jalvesaq** [comment]
It should be fixed now.
