### ISSUE TITLE
Rhelp is not working with vimpager

### ISSUE THREAD

**Issue by Figuera** [jcfaria/Vim-R-plugin#190]
:Rhelp (and \rh) returns nothing (not even any messages) if vimrplugin_vimpager is set to anything other than "no".

I tried to manually call ":call AskRDoc("lm","",0)" and that also returns nothing.

PS: Another, peharps correlated, problem is that if I start vim with --servername tag than the help() command (inside R) returns nothing. But that problem is solved if I start vim with no tags.

**Comment by jalvesaq** [comment]
What is your operating system?
After starting R, what is the output of `:messages`?
What Vim are you using (did you compile it)?

**Comment by Figuera** [comment]
Ubuntu 14.04
If I start vim with --servername tag than there is no message but the usual "where you are" messages.
If I start vim without --servername tag than there is a message telling me to use servername:
"Example: vim --servername XXXX"
Vim 7.4, compiled (Huge)

**Comment by Figuera** [comment]
I get it!

The servername tag was the real problem, I had the alias vim="vim --servername VIM" in my .bashrc, but I forgot that I was using zsh, I put it in .zshrc and now everything is working fine.

Thanks anyway jalveaq.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
