### ISSUE TITLE
Clear R console input before send R code from vim

### ISSUE THREAD

**Issue by Figuera** [jcfaria/Vim-R-plugin#193]
I don't know if here is the right place to put this, or if I can resolve this in any other way.

But a annoying common problem that I face while using Vim R Plugin is when I send some line, function or file from vim to R console and there is already some type of input in R console. Result? The two texts merge together in a not existing command, therefore error, and I have to send it again.

Example:

I was in de middle of asking for the mean of some variable, so the R console is like this:

> mean(n)

But than I change the focus to Vim, change some function and send it back to R, this is what I get:

> mean(n)base::source("blablabla")
Error: unexpect symbol in mean(n)base

I just want that before any send command the R console input is cleared, and the command passes without errors.

PS: This is even a bigger of a problem with \rq and \rw, the command send the quit function to R console, but, if anything at all is written in the R console, it fails to quit, even thought vim thinks that the R console is already closed.

**Comment by jalvesaq** [comment]
Please, see the option `vimrplugin_ca_ck`. Its name isn't intuitive, but it does what you want.

**Comment by Figuera** [comment]
Thank you, that is exactly what I was looking for.

**Comment by Figuera** [comment]
Sorry to bother you again, but I am now using tmux and ca_ck do not work. I notice that c-w seems to have the desire effect. But I dont know if Vim-R-Plugin can prepends this 'keys' before the actual command.

**Comment by jalvesaq** [comment]
The Vim-R-plugin is no longer being developed. You have to try Nvim-R. If it is affected by this issue too, you have to report the problem there.
Note that in Tmux you have to press `Ctrl-A` twice to get a single one if this key combination is your Tmux prefix.
