### ISSUE TITLE
Sending command starting with a - (minus) sign

### ISSUE THREAD

**Issue by songcai** [jcfaria/Vim-R-plugin#195]
When I send an R command starting with a minus sign, say
   -15/3
from Vim to a console, I always get the following error in Vim:
   set-buffer: illegal option -- 3 usage: set-buffer [-a] [-b buffer-name] [-n new-buffer-name] data
and the command is not sent.

I test this on both Mac OS X El Capitan and Debian Stable (jessie), the problem is exactly the same.
Vim version:  7.4.936
Vim-R-plugin: Git version downloaded on Nov. 30, 2015 with Git versions of VimCom and colorout downloaded on the same date.

**Comment by jalvesaq** [comment]
A space before the `-` should never cause any harm... Thanks for reporting the bug.

**Comment by songcai** [comment]
Thanks for the trick!

**Comment by songcai** [comment]
I noticed that the issue has been fixed in the development version. Thanks a lot for the prompt update!
