### ISSUE TITLE
Ignoring Environment Variables on Windows

### ISSUE THREAD

**Issue by siqi-liu** [jcfaria/Vim-R-plugin#196]
On Windows 8.1, when the environment variable HOME is set to be different from the default, if starting R alone (without Vim), HOME is correctly set, but if starting with Vim-R-plugin, it is the same as the default. Is this a bug or I missed something?

P.S. I need to set this so that I can install the packages at a different location than the default. 

Thanks in advance.

**Comment by jalvesaq** [comment]
Did you try to set the environment variable `R_LIBS_USER`. I use Linux, and I have in my `~/.bashrc`:
```
export R_LIBS_USER=~/.cache/R
```

**Comment by siqi-liu** [comment]
Thanks. Setting `R_LIBS_USER` works. It is not exactly the same as setting `HOME` or `R_USER` (for example, `.Rprofile` still needs to be at the default location), but it did solve my problem. Would you mind if I ask why the R instance started with Vim-R-plugin ignores `HOME` and `R_USER`?

**Comment by jalvesaq** [comment]
I would have to reboot the computer to check, but as far as I remember, the `HOME` environment variable in GVim is set to `C:\Users\login` while in R it is set to `C:\Users\login\Documents`. If the plugin did not change the value of `HOME` while starting R, then, R would look for the Rprofile in different places.

However you are right in that I could check the value of `R_USER` and give priority to it if it was set. I will see this later.

**Comment by jalvesaq** [comment]
Please, read, `help(Startup)` in R. It seems that you should set `R_PROFILE_USER`, and that I should keep setting `HOME`, but I am not sure.

**Comment by siqi-liu** [comment]
Thank you for pointing that out. As far as I understand, `R_PROFILE_USER` is a user-specific path for `.Rprofile`, like `R_LIBS_USER` is a user-specific path for R packages. On the other hand, if those are not set, `R_USER` and `HOME` should be a user-specific base-path for searching `.Rprofile` and R packages. Setting `R_PROFILE_USER` and `R_LIBS_USER` should solve the problem, but it is kind of a workaround.

The thing that puzzles me is that when `HOME` or `R_USER` is set, when I execute
`Sys.getenv('HOME')`
in a standalone R instance, it returns the value I set. But when I run the same command in an R instance started by Vim-R-plugin, it returns the default value. `C:\Users\<username>\Documents`.

**Comment by jalvesaq** [comment]
Please, see the file r-plugin/windows.vim. `HOME` is set there. Currently, it is hardcoded as the Windows register value for "Personal" "Shell Folders". If I do not set it, it will be worse for most users because its value will be `C:\Users\<username>` which is different from the default value set by R. Ideally, I would unset it before starting R, but I do not know how to unset `HOME` in GVim. If nobody finds a solution for this, what I can do is create a new option for Windows: `vimrplugin_set_home_env`. If its value were 0, the plugin would not set `HOME`.

**Comment by siqi-liu** [comment]
Okay, that makes sense. I think even if you can unset `HOME`, it won't work because R still won't get the value specified by the user. Also, you cannot tell by looking at the value whether it's intentionally specified by the user or just the default from Vim. So It's probably better to have an option and also mention it in the help file.

**Comment by siqi-liu** [comment]
Also, thank you for the help.

**Comment by jalvesaq** [comment]
I implemented the option `vimrplugin_set_home_env`: https://github.com/jcfaria/Vim-R-plugin/commit/e8c8b359066d5eb508997a9b773600c7aa1acedf
Thanks for reporting the issue!
