### ISSUE TITLE
Running R code in Roxygen example sections does not work for visual selections

### ISSUE THREAD

**Issue by jranke** [jcfaria/Vim-R-plugin#197]
I speculate that this may be the case because the function CleanOxygenLine is not called in the function SendSelectionToR in r-plugin/common_global.vim. Instead there is a substitute command on line 1774 that was also introduced in 136738faad9966079e3c05c140845ed594299c25.

I tried to understand and fix myself, did not succeed. Thanks for all your work on this so far!

**Comment by jalvesaq** [comment]
It works here. I selected with `<Shift-V>` only the lines that are supposed to be run in the example below and pressed the space bar (which is mapped to `<Plug>RDSendSelection` in Visual mode). The code was copied into a temporary file and sourced:

```
#' This is not an example section
#' 
#' This is a basic form
#'
#' @examples
#' xx <- rnorm(100)
#' yy <- rnorm(100)
#' mm <- lm(yy ~ xx)
#' summary(mm)
#'
#'
#'
#' @somethingmore
#' 
```

**Comment by jranke** [comment]
Thanks for you quick reply. As you may remember, I like the mapping 'r' for sending the visual selection. As I have

    let vimrplugin_map_r = 1

in my .vimrc, I have the following mapping:

    v  r           *@<Esc>:call SendSelectionToR("silent", "down")<CR>

However, when I select code in the example above, the code gets pasted, but there is no substitution of the roxygen comments, so the code is not executed.

**Comment by jalvesaq** [comment]
It works for me if I put in my vimrc
```vim
let vimrplugin_map_r = 1
```
or
```vim
vmap  r  *@<Esc>:call SendSelectionToR("silent", "down")<CR>
```
But it does not work with
```vim
v  r  *@<Esc>:call SendSelectionToR("silent", "down")<CR>
```

**Comment by jranke** [comment]
What I pasted:

    v  r           *@<Esc>:call SendSelectionToR("silent", "down")<CR>

was the output line from the :map command which I believe is generated by using

    let vimrplugin_map_r = 1

in my .vimrc. Also, the mappings for SendSelectionToR

```
v  ,so         *@<Esc>:call SendSelectionToR("echo", "stay", "NewtabInsert")<CR>
v  ,sa         *@<Esc>:call SendSelectionToR("echo", "down")<CR>
v  ,se         *@<Esc>:call SendSelectionToR("echo", "stay")<CR>
v  ,ss         *@<Esc>:call SendSelectionToR("silent", "stay")<CR>
```

do take out the roxygen comments.

**Comment by jalvesaq** [comment]
Sorry, but I can't reproduce the bug. Are your vim runtime files up to date?

**Comment by jranke** [comment]
Yes, they are... strange...

**Comment by jranke** [comment]
OK, it seems to be a bit more complicated. When I have 

    let vimrplugin_map_r = 1

towards the beginning of my `.vimrc`, it does not work at all. If I put it at the end, 
after marking a single line of the example code, I see in the R console

    > #' xx <- rnorm(100)

but `xx` is actually defined!

However, when I select the same line (with Shift-V), and send it with `,se`, I get the same output, but it is not executed, i.e. xx is not defined in the R console!

**Comment by jranke** [comment]
I am using pathogen and moving the line

execute pathogen#infect()

which defines the runtimepath towards the top of `.vimrc` has the same effect.

**Comment by jranke** [comment]
Maybe this observation can help to debug. I am using the example that you gave, saved to a file called 'test.R', and the plugin correctly sets the filetype to 'r'. My localleader is `,`.

When I select a single line, and issue the command `,se`, there is no substitution of the roxygen comment. When I select more than one line, the substitution is applied, and the command is correctly executed!

**Comment by jalvesaq** [comment]
I couldn't see the issue before because I only send a selection of a single line to R when I want to send only part of the line. I believe the bug if fixed now. Thanks for reporting it!

**Comment by jranke** [comment]
When sending several lines, it was not checked if they are in an example section and there was only a simple substitution of #' (##' was not substituted).

**Comment by jalvesaq** [comment]
I fixed the first problem.

**Comment by jranke** [comment]
Mhm, that may well be, I admit I did not really check, sorry - anyway I think it is fine now - thanks again! Johannes
