### ISSUE TITLE
tmux -V not available on OpenBSD

### ISSUE THREAD

**Issue by feinerer** [jcfaria/Vim-R-plugin#200]
On a current OpenBSD system, tmux does not have the "-V" option for displaying its version (see e.g., http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/tmux.1?query=tmux). Consequently the call system("tmux -V") in common_global.vim (https://github.com/jcfaria/Vim-R-plugin/blob/master/r-plugin/common_global.vim#L3258) fails and Vim-R-plugin refuses to work ("Vim-R-plugin requires Tmux >= 1.8").

When disabling the version check, Vim-R-plugin starts and works fine.

Please note that this is not a matter of having an outdated version of tmux in OpenBSD. tmux is part of the base OpenBSD system and development happens there. A viable solution could therefore to just skip the version check on OpenBSD.

**Comment by jalvesaq** [comment]
Is it fixed now? Please, see: https://github.com/jcfaria/Vim-R-plugin/commit/b07faa37e13288ee99645a88aa7356bc96ef1c38

**Comment by feinerer** [comment]
Yes, fixed. Thank you!
