### ISSUE TITLE
[Regression] StartR fails with vim-r 1.2.9

### ISSUE THREAD

**Issue by protist** [jcfaria/Vim-R-plugin#203]
I just upgraded to vim-r 1.2.9 (and vimcom 1.2-9). However, `<leader>rf` no longer works, with r not starting. I get the following error.

```
Error detected while processing function StartR:
line 104:
E117: Unknown function: StartR_TmuxSplit
```

I tried rolling back to vim-r 1.2.8 (and vimcom 1.2-8) and tried `<leader>rf`. This works, and vim-r and r work as expected, although I do see an error that I don't recall seeing before.

    Error [vimcom]: Invalid message received: B Update OB [StartR]

FWIW there was a recent update in vim, from 7.4.1386-1 to 7.4.1529, so I also tried reverting this. However, the most recent vim-r 1.2.9 also fails here.

**Comment by jalvesaq** [comment]
Sorry! I forgot to add some new files to the vimball. Please, check version 1.3.0.

**Comment by protist** [comment]
No problem! It works perfectly now. Thank you!
