### ISSUE TITLE
Start 'tmux' before Vim. The X Window system is required to run R in an external terminal.

### ISSUE THREAD

**Issue by DadongZ** [jcfaria/Vim-R-plugin#205]
Hi There, I am still using the previous Vim-R-Plugin version and pretty comfortable about it settings. Recently I upgraded the linux system and got message never before "Start 'tmux' before Vim. The X Window system is required to run R in an external terminal.". The issue is, if I start tmux manually, the vim background were also changed weirdly and furhter ,rc will start a R console in a split window rather than a new window. Do you have some suggestions?

**Comment by jalvesaq** [comment]
I am sorry, but this plugin is no longer maintained. Please, switch to [Nvim-R](https://github.com/jalvesaq/Nvim-R). 

In Nvim-R, R will start in an external terminal emulator by default if you are using Vim.
If using Neovim, put in your vimrc:

```
let R_in_buffer = 0
```

If you want to run R in a Tmux split, put in your vimrc:

```
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
```
